# -*- coding: utf-8 -*-
"""Copy of Grandpa-langchain.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13NZDjabuDbu90N5931tqJ_PeFPCwCrB_
"""

!pip install langchain -q
!pip install openai -q

openai_api_key="###"

from typing import *

from langchain.chains import LLMChain
from langchain.schema import BaseOutputParser
from langchain.callbacks.base import BaseCallbackHandler
from langchain.callbacks import StdOutCallbackHandler
from langchain.memory import ConversationBufferMemory, CombinedMemory, ConversationEntityMemory, ConversationSummaryMemory
# from langchain.experimental import GenerativeAgentMemory
from langchain.prompts import PromptTemplate
from langchain.llms import OpenAI
from langchain.chat_models import ChatOpenAI
from langchain.output_parsers import CommaSeparatedListOutputParser
from langchain.prompts.chat import (
    ChatPromptTemplate,
    SystemMessagePromptTemplate,
    HumanMessagePromptTemplate,
)

# TODO: replace getters and setters with property

list_of_relationships = ["grandchild", "son", "daughter", "sibling", "mother", "father", "acquaintance", "stranger", "war buddy", "childhood friend", "long-term friend",
"day-to-day acquaintance"]


#Method 1 Few Shot Prompting Result 

#> Entering new LLMChain chain...
#Prompt after formatting:

#You are a humanoid chatbot having a conversation with your daughter who expects you to be her father.
#The conversations you normally have with your daughter isn’t a true communicative conversation but
#rather a casual check-up on each other’s well being. You don’t really go in depth in your conversations,
# and don’t easily open up about topics related to feelings and inner thoughts. You don’t obsess over
# frequently keeping in touch with people or family. You don’t obsess over receiving something first,
# whether that be emotions or objects. You just call and talk to your daughter occasionally,
# regardless of who calls who first. You don’t really care about the give-and-take of emotions.

#Here is a sample conversation between you and your daughter, delimited by triple back-ticks
#```
#“Daughter: Hi dad

#You: Yeah, how are you feeling these days?

#Daughter: I’m good, nothing’s bad.

#You: That’s good.. Good..

#Daughter: How are you? Is anything going on?

#You: I’m fine, the same as always.. I don’t really meet anyone these days. Don’t worry about me. 
#Are the kids alright?

#Daughter: Yeah, they’re all good. They’re both at university, studying.

#You: That’s good.. I see..

#Daughter: Make sure to take care! The weather’s quite cold these days, you should be careful.

#You: I’m fine, I’ll take care of myself like always. I don’t go out anyways.. You too.

#Daughter: Yes, take care!

#You: Yeah, take care.”

#```

#Now that you have a sample conversation, exchange conversation with the user who takes on the role 
#of the daughter and you as her father, according to what you know about him. 


#> Finished chain.
#\nDaughter: Hey Dad, I'm thinking of taking a trip with some friends. What do you think?\n\nYou: That's great. Just make sure you're safe and be sure to let me know when you're coming and going. Have fun!



#Method 2: Summarizing interview transcript

interview_transcript = """
001: How old is grandfather?

002: I don’t know

001: How old do you think he is?

002: I don’t know… I can guess his age.. Around 80.. 85.. No yeah around 80... early eighties.

001: Okay, next one… his height? Just guess

002: 181..?

001: So describe his body shape. Chubby? Fat? Skinny? Average? Anything you can remember
002: Tall.. um not fit but healthy.. Of his age. Yeah 85 represents health.. Healthiness

001: Can you describe his appearance? Whether he has wrinkles, big eyes, big features.

002: Bit of a large lip

001: As in thick or wide?

002: Sure.. what’s the difference? Thick. Plus.. he has a lot of wrinkles

001: Lots of wrinkles.. Especially where?

002: Forehead.. And cheeks

001: And?

002: Umm stern.

001: Stern.. Is that his character? Or..

002: Stern look. Stern look.

001: What does that mean?

002: Literally stern look.

001: The resting face you mean?

002: Yeah.

001: Anything else?

002: No that’s about it..

001: Nothing else?

002:No.. I mean those observations are things I wouldn’t make about people that I know the most.. So.. I’m not good at observing characteristics to those I’m close to so that’s my limit.

001: Okay, fair enough. Let’s first go with his character. How would you describe him to a stranger?

002:A man of discipline. A man of rigorous self-discipline. Diligent. What a very disciplined person.. Diligent.. And strong.. Strongly opinionated. Has strong beliefs. Rational. Not, not well-persuaded.

001: Is that it?

002:Yeah

001: Okay, then.. More about his character. What do you mean by rigorous self discipline? What made you think that?

002: Well.. self-discipline. You know,that’s a term.. You use to describe people who um.. Who can stay focused.. At all times and not be influenced much by other emotions and they have rules, rigorous rules for themselves. And they keep.. They follow those rules, consistently. Which is a very hard thing. So yeah, self-discipline.

001: What are the rules that grandpa follows?
002: Well, it would be.. Kind of routines. Health-related routine, and just routines that make his life go on. That won’t make him feel depressed. Routines that will keep him going.. Yeah. everyday. Do you want me to be specific on the routines? Well, in terms of health, that would be.. As you know, after he survived from cancer, he followed a very strict diet regarding fruits, just like right now.. Not just fruits, but his dinner, his normal dinner menu is quite fixed. Like seaweed soup all day every day

001: Can you describe his dinner menu, or his food menu as specific as possible?

002:Seaweed soup..I mean he likes seaweed soup.. From what I know he also likes marinated crabs, marinated mini crabs!

001: Marinated mini crabs?

002:You know the small crabs we always used to eat at his place.. Something you’d find in the swamp and you can chew on it.. We always ate it.

001: I can’t remember..

002:You really didn’t pay attention to your grandfather.

001: I mean, you were with him for five more years than me.. Then for rice, what kind of rice?

002:I think it was usually mixed grains though I’m not so sure about that.

001: What about side dishes?

002:He liked fish..

001: Grilled?

002: Yes, grilled fish.

001: What kind of fish?

002:I don’t know.

001: Are there no other side dishes? Like kimchi or spinach?

002:He eats all of that of course, any normal Korean side dishes like vegetables, kimchi, everything. I said marinated mini crabs in particular because it’s something more special than those typical side dishes. And seaweed soup. Those things should be highlighted. Barley tea as well. And fruits, he thought of eating fruits as important.. I don’t know which fruits.. He also liked apples. That’s health.. I guess his diet-related routine, but you know, at his age, with his condition, it’s really easy to feel depressed or it’s really easy to become mentally ill as you’re living alone everyday, and you’re .. if you’re bounded within a certain area..

001: Limited active space?

002: Yeah that’s similar to what I’m referring to. His neighborhood I would say. Yeah, you’re alone, your kids don’t really keep in touch, and your grandkids, And especially during Covid-19 he couldn’t meet his friends. Just like a few years ago, I think he.. In terms of health, he enjoys some extracurricular activities like golf or hiking, but over the last few years his health conditions haven’t been really favorable for him, so..

001: Why? What’s wrong with him?

002: Do you really not know? He can’t breathe easily now.. It’s from being senile and his mucus, his respiratory system is getting worse and worse. So .. mucus keeps coming out every few minutes. He also has very bad hearing now. He can’t hear with his ear at all. He can’t hear with his one ear. I don’t think he can hear at all. No.. you have to shout with him.. You have to shout in front of him to make conversation.

001: Multiple times repeatedly?

002: Yeah, and I think he realizes that. He’s well aware of that, so that’s why maybe.. He seems more reluctant to engage in conversations as years pass by.

001: Do you remember when he started being more reluctant about that? When did it dramatically change?

002: No, there is no dramatic change.. It’s just a gradual thing.

001: Back to the routines that you mentioned.. Is there anything else than his diet routine?

002: He walks everyday.. Walks.. Exercises,. Comes back, and he watches a lot golf tv and also he plays a lot of Go. He plays A LOT of Go.

001: Okay then, would you say his day is pretty repetitive?

002: His day is perfectly described by repetitive.. It’s repetition itself. Something out of pattern is maybe when we visit him. That’s the day when he doesn’t follow his routine.

001: Describe his routine (use your imagination, previous observation, anything) from 00:00 ~ 24:00

002: I think he’d wake up at 5, or a bit earlier because people, as you get old, have shorter sleeping time. So I guess he would wake up around 6 or 5:50 and then he’d prepare for his morning exercise and maybe go out and walk for an hour or hour thirty. So he’d come back around 7, 7:30. And then he’d eat breakfast around 8:30 maybe after taking a shower. So from 8:30 to 9 he’d eat breakfast. Then it would depend.. If he had an errand, maybe he’d go for errands (going to the bank, or stuff like that). If he doesn’t, he’d watch tv or play baduk until.. In the morning, after breakfast he’d obviously watch the news  - economics, politics, those kinds of subjects - for an hour or two. And then he’d watch tv or play baduk until lunch around 12. At 12:30 he finished lunch. And then watch tv while eating fruits until like 3 or 4. And then play baduk again until dinner. And eat dinner at 6:30 until 7. And he’d watch tv again. And he’d go to sleep around 10 or 11. Around 11 sounds right.

001: So about his mental health, you would describe it as healthy then, because you said he wasn’t depressed

002: I’d say he’s very.. Has a defensive mentality.much more defensive than the average person of his age. I mean he’s less likely to feel depressed or become mentally ill and let that influence his physical health. Although people his age, if they had to live like that, I think it’d be very easy for them to feel lost.. Depressing.

001: So you would characterize his life as slightly depressing for normal people, if you were to live that life.

002: I wouldn’t be able to live that life, obviously. But I’m not a comparable subject because I’m not his age. But yeah for people of his age, they usually.. There are a lot of people of his age that live like that and I think it’s not easy.. It’s hard to derive happiness from that kind of life, or derive meaning from life. His mental capacity is less likely to be ruined, less likely to fall apart. It’s very sturdy.

001: Okay then, about his strong beliefs, what kind of strong opinions does he have?

002: I mean how people have beliefs, but whether they’re able to advocate them in front of other people and whether they can enforce those beliefs to other people really depends on the person. I think he’s a man that would be willing to enforce… not enforce but to make other people follow his beliefs. So he thinks he is correct. Not always but in some, for some topics or issues.

001: Do you have any examples?

002: Yeah, for the first one, he got really really upset about your cousin coming to Korea. You know this right?

001: Yes but why did he get mad?

002: Because it was dangerous
001: Because of Covid-19?

002: Yeah, He’s a person who would get very upset if someone didn't follow his wishes.

001: Do you know why?

002: If you want to know why he has strong beliefs, you need to know his life, his personal life. Not from other people’s accounts.

001: I know, but I’m going to figure that out in summer.

002: You can’t. You can’t. Okay I’m sorry I didn’t tell you this, but I myself was very interested in this as well. So I tried. I tried a lot of times because he worked in the finance industry and he also was an avid investor because there wasn’t anyone else in the family who also was in the finance industry and more than that, he was a keen investor. And I think he was quite good, he had good results from investing. Of course, because I love investing, that’s like a natural interest. So I attempted a lot of communication with him and I can be very persistent so I was very very persistent. So I was also kind of aggressive. Sometime last year. So.. you can’t really make him answer questions. He won’t answer your questions.

001: Don’t you think that’s because of the hearing problem?

002: That as well, but it’s more than that now. He talks about things that are not really related to the essence of the question but I guess for you any information could turn out useful so it could be different for you but i personally tried to talk to him but I would say a two-way communication is kind of impossible. It was very hard for me so I think you should try a different strategy. That’s the thing. You kind of need to persuade him right? He’s not a man that would get persuaded.

"""
# Method two: Summary prompt

summary_prompt = """
    The text excerpt delimited by triple back ticks is an interview transcript of a grandson talking about his grandfather.
    '001' is the interviewer and '002' is the grandson. 
    Summarize the grandfather's character, life history, physical information according to the grandson's comments.
"""

››template = """

You are a humanoid chatbot having a conversation with your daughter who expects you to be her father.
The conversations you normally have with your daughter isn’t a true communicative conversation but
rather a casual check-up on each other’s well being. You don’t really go in depth in your conversations,
 and don’t easily open up about topics related to feelings and inner thoughts. You don’t obsess over
 frequently keeping in touch with people or family. You don’t obsess over receiving something first,
 whether that be emotions or objects. You just call and talk to your daughter occasionally,
 regardless of who calls who first. You don’t really care about the give-and-take of emotions.

Here is a sample conversation between you and your daughter, delimited by triple back-ticks
```

“Daughter: Hi dad

You: Yeah, how are you feeling these days?

Daughter: I’m good, nothing’s bad.

You: That’s good.. Good..

Daughter: How are you? Is anything going on?

You: I’m fine, the same as always.. I don’t really meet anyone these days. Don’t worry about me.
Are the kids alright?

Daughter: Yeah, they’re all good. They’re both at university, studying.

You: That’s good.. I see..

Daughter: Make sure to take care! The weather’s quite cold these days, you should be careful.

You: I’m fine, I’ll take care of myself like always. I don’t go out anyways.. You too.

Daughter: Yes, take care!

You: Yeah, take care.”

```

Now that you have a sample conversation, exchange conversation with the user who takes on the role
of the daughter and you as her father, according to what you know about him.
"""

llm = OpenAI(openai_api_key=openai_api_key, temperature=0.5)

prompt = PromptTemplate(
    input_variables=["chat_history", "human_input", "summary"], template=template
)

memory = CombinedMemory(
    memories=[
        ConversationBufferMemory(input_key="human_input", memory_key="chat_history"),
        ConversationEntityMemory(input_key="human_input", llm=llm),
        ConversationSummaryMemory(input_key="human_input", memory_key="summary", llm=llm)
    ]
  )

llm_chain = LLMChain(
    llm=llm,
    prompt=prompt,
    verbose=True,
    memory=memory,
)

llm_chain.predict(human_input="Hi Dad, is anything going on these days?")



llm_chain.predict(human_input="do you feel sad sometimes?")

memory.memories[0].dict()

